language: java
script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_JOB_ID
  - echo $TRAVIS_JOB_NUMBER
  - echo $TRAVIS_BUILD_ID
  - echo $TRAVIS_BUILD_NUMBER
